baseURL = "/"
title = "Mafrinha"
theme = "manis"

# Copyright notice. Note: You can use HTML tag here
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
paginate = 10

# Your disqus shortname
disqusShortname = ""

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[menu]
	[[menu.main]]
		name = "About"
		url = "/about"

[taxonomies]
	tag = "tags"

[params]
	# If false, use minified CSS (ui.min.css)
	debugCSS = false
	# Custom CSS
	customCSS = []

	# Utterances Configuration
	utterancesRepo = ""
	utterancesTheme = "github-light"
	utterancesLabel = ""
	
	# List of sections support disqus comments
	disqusSections = [ "blog" ]
	# Site meta description
	description = "Thoughts and adventures of a frontend engineer and sometimes enterpreneur."
	# Site's Tagline (Subtitle or Keyword)
	tagline = "aka Diogo Mafra."
	# If true give attribution to this theme
	themeAttrib = false
	# URL to license file, can be outside of your domain
	# licenseURL = "/about/license"

	# Configure which sections for Latest Posts
	# mainSections = ["blog", "post"]
	postSection = "post"
	# Configure which sections for Latest Works
	workSection = "work"

	# 404 Configuration
	head404 = "Sorry, You can't always get what you want."
	sub404 = "You get <a href='/'>what you need</a>."

	# Color of your website's accent
	colorTheme = "#e36209"
	# Maximum number of item in Latest Posts or Works
	latestCount = 3
	# Path to site's favicon image
	faviconImg = "https://pbs.twimg.com/profile_images/1228090358468349952/wtO_sYYx_400x400.jpg"
	# Date format in item list
	dateFmt = "Jan 02, 2006"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = ["jsx", "react", "javascript", "json", "typescript", "yaml" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "diogomqbm13@gmail.com"
	github = "https://github.com/diogomqbm/"
	twitter = "https://twitter.com/diogomqbm_"


# Language Configuration
#[languages.in]
#	lang = "in"
#	languageName = "Bahasa Indonesia"
#	weight = 1
